#!/usr/bin/env ruby
# encoding: UTF-8

# Read "20130103-stevilke_final.csv" and build PHP / Ruby arrays.

require "bundler/setup"
require 'csv'
require 'pry'
# binding.pry

csv = CSV.open("../data/20130103-stevilke_final.csv","rb:utf-8")
php = File.open("../data/postcodes_si.php","w")
js = File.open("../data/postcodes_si.js","w")

# Write headers
php.write "<?php /* Generated by #{__FILE__} */ $postcodes_si=array(); \n"
js.write "/* Generated by #{__FILE__} */ \nvar postcodes_si = new Array(); \n"

csv.to_a.sort! {|a,b| a.first<=>b.first }.each_with_index do |row,i|
	postcode, town, org, state, lat, lng = row

	php.write "$postcodes_si[#{postcode}]=array('town'=>'#{town}','lat'=>#{lat},'lng'=>#{lng},'org'=>'#{org}');\n"

  js.write "postcodes_si[#{postcode}]={town: '#{town}', lat: #{lat}, lng: #{lng}, org: '#{org}', postcode: #{postcode} };\n"
end


php.write "//eof"
js.write "\n"

php.close
js.close
