#!/usr/bin/env ruby
# encoding: UTF-8

# Read "20130103-stevilke_final.csv" and build PHP / Ruby arrays.

require "bundler/setup"
require 'csv'
require 'pry'
# binding.pry

csv = CSV.open("../data/20130103-stevilke_final.csv","rb:utf-8")
php = File.open("../data/postcodes_si.php","w")

# Write headers
php.write "<?php /* Generated by #{__FILE__} */ $postcodes_si=array(); \n"

csv.each_with_index do |row,i|
	postcode, town, org, state, lat, lng = row
	php.write "$postcodes_si[#{postcode}]=array('town'=>'#{town}','lat'=>#{lat},'lng'=>#{lng},'org'=>'#{org}');\n"
end

php.write "//eof"

php.close

